apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odysseus
  namespace: odysseus
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare-dns01
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - odysseus.rafstack.com.br
      secretName: odysseus-tls
  rules:
    - host: odysseus.rafstack.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: odysseus
                port:
                  number: 7000
