apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odysseus
  namespace: odysseus
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - odysseus.redbeauty.com.br
      secretName: odysseus-tls
  rules:
    - host: odysseus.redbeauty.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: odysseus
                port:
                  number: 7000
